package com.bananaforscale;

import jasmin.ClassFile;
import org.antlr.v4.runtime.ANTLRFileStream;
import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Scanner;

/**
 * This is the compiler for the language Banan4S
 * Authors: Jonas Buerkel, Jannik Franz, Stefan Hill
 * Group: Banana For Scale
 * DHBW Stuttgart, TINF13A
 *
 */
public class Compiler
{
    /**
     * This is the main method of the Banan4S compiler
     */
    public static void main(String[] args) throws Exception {
        ANTLRInputStream input;
        if (args.length > 0)
            input = new ANTLRFileStream(args[0]);
        else
            input = new ANTLRFileStream("code/demo.code");
        System.out.println(compile(input));
    }

    /**
     * This is the method compile
     * the ANTLR input stream is given to, lexer and parser are started in this method
     * a loop is started which runs every line of code separately through the compiler, creates jasmin code
     * the aggregated code is written into the jasmin.j file which is executed afterwards
     * if an error messages occurs in one code line, the loop is stopped and the error message is written on the console
     *
     * else, the (final result OR all results?) is written in the console
     *
     * @param input: the incoming ANTLR input stream
     * @return (final result OR all results?) / error message if error occured
     * @throws Exception
     */
    public static String compile(ANTLRInputStream input) throws Exception {
        BananaCompilerLexer lexer = new BananaCompilerLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        BananaCompilerParser parser = new BananaCompilerParser(tokens);

        ParseTree tree = parser.prog();

        String text, result;
        //Loop (while not last line of source code && error != "writing jasmin file failed"
        BananaVisitor visitor = new BananaVisitor();
        text = createJasminCode((visitor.visit(tree)), visitor.getErrorMessage());
        writeJasminFile(text); //override last result, always latest result stored in variable
        result = executeJasmin(text);
        //Loop end

        //return latest result
        return result;
    }

    /**
     * This method creates the code for the jasmin file
     * @param instructions: the incoming instructions generated from the source code by the visitor
     * @param errorMessage:
     * @return adjusted jasmin code (for calculations: added printstream, else: only added line separator)
     */
    private static String createJasminCode(String instructions, String errorMessage) {
        String output;
        if (!errorMessage.equals("")) {
            output = "getstatic java/lang/System/out Ljava/io/PrintStream;" + System.lineSeparator() + "ldc \"" + errorMessage + "\"" + System.lineSeparator() + "invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V" + System.lineSeparator();
        } else {
            //output = "getstatic java/lang/System/out Ljava/io/PrintStream;" + System.lineSeparator() + instructions + System.lineSeparator() + "invokevirtual java/io/PrintStream/println(I)V" + System.lineSeparator();
            output = instructions + System.lineSeparator();
        }

        return ".class public Test" + System.lineSeparator() +
                ".super java/lang/Object" + System.lineSeparator() +
                ".method public static main([Ljava/lang/String;)V" + System.lineSeparator() +
                ".limit stack 100" + System.lineSeparator() +
                ".limit locals 100" + System.lineSeparator() +
                output +
                "return" + System.lineSeparator() +
                ".end method";
    }

    /**
     * This method writes the generated jasmin code instructions in the file jasmin.j (path: bananacompiler/jasmin.j)
     * @param text: jasmin code that will be written in the jasmin.j file
     */
    private static void writeJasminFile(String text){

        PrintWriter pw = null;

        try {
            pw = new PrintWriter(new BufferedWriter(new FileWriter("code/jasmin.j")));
            pw.println(text);
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } finally {
            if (pw != null){
                pw.flush();
                pw.close();
            }
        }
    }

    /**
     * This method executes the jasmin code generated by this compiler
     * @param code: jasmin code that will be executed
     * @return output of jasmin code
     * @throws Exception
     */
    public static String executeJasmin(String code) throws Exception {
        createTempDir();
        ClassFile classFile = new ClassFile();
        try {
            classFile.readJasmin(new StringReader(code), "", false);
        } catch (Exception e) {
            return "Failed to read bytecode: " + e.getMessage();
        }
        Path outputPath = tempDir.resolve(classFile.getClassName() + ".class");
        try {
            classFile.write(Files.newOutputStream(outputPath));
        } catch (Exception e) {
            return "Failed to write program: " + e.getMessage();
        }
        String result = runJavaClass(tempDir, classFile.getClassName());
        delete(tempDir.toFile());
        return result;
    }
    /**
     * The private attribute tempDir stores the Path of the temporary directory
     * this directory is created in the method createTempDir() and used in the method executeJasmin(...)
     */
    private static Path tempDir;
    /**
     * This method creates temporary directory which will be used for the created .class file of the jasmin code
     */
    public static void createTempDir() throws IOException {
        tempDir = Files.createTempDirectory("compilerTest");
    }
    /**
     * This method deletes the temporary directory created in the method createTempDir() and used in the method executeJasmin(...)
     * @param file: the directory which is to be deleted
     */
    public static void delete(File file) {
        if (file.isDirectory()) {
            //directory is empty, then delete it
            if (file.list().length == 0) {
                file.delete();
                System.out.println("Directory is deleted : "
                        + file.getAbsolutePath());
            } else {
                //list all the directory contents
                String files[] = file.list();
                for (String temp : files) {
                    //construct the file structure
                    File fileDelete = new File(file, temp);

                    //recursive delete
                    delete(fileDelete);
                }
                //check the directory again, if empty then delete it
                if (file.list().length == 0) {
                    file.delete();
                    System.out.println("Directory is deleted : "
                            + file.getAbsolutePath());
                }
            }
        } else {
            //if file, then delete it
            file.delete();
        }
    }
    /**
     * This method runs the .class file generated by the jasmin code and returns the result of the according operation
     * @param dir: tempDir which is used to store the .class file created by the jasmin code
     * @param className: name of the class created by the jasmin code
     * @return output of the executed jasmin code which is the result of the operation from which the jasmin code was generated
     * @throws Exception
     */
    private static String runJavaClass(Path dir, String className) throws Exception {
        Process process = Runtime.getRuntime().exec(new String[]{"java", "-cp", dir.toString(), className});
        InputStream in = process.getInputStream();
        return new Scanner(in).useDelimiter("\\A").next();
    }
}
